# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - microhack-dev-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build and test
        env:
          NODE_ENV: production
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Prepare deployment package
        run: |
          mkdir -p deploy/frontend
          cp -r node_modules deploy/
          cp -r frontend/build deploy/frontend/
          cp package.json deploy/
          cp .node-version deploy/
          cp server.js deploy/
          cp database.js deploy/
          cp database-mysql.js deploy/
          cp azure-storage.js deploy/
          cp -r images deploy/ 2>/dev/null || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'microhack-dev-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_907B482C22A64CD890E354B9ED3ECB98 }}